### ISSUE TITLE
Auto update no longer functioning

### ISSUE THREAD

**Issue by texpatnyc** [open-source-labs/Swell#302]
**Problem**
There is a bug that is causing an error in the `gh-publish` script which creates the release in github & uploads all the download files.  The errors in the running of the script are causing the following files to not be uploaded to GitHub as part of the release:
- latest-linux.yml
- latest-mac.yml
- latest.yml

These 3 files are needed for the Auto-Updater to work properly.  Currently anyone running < v0.8.0 will have to redownload the new v0.9.0 to get the new features without this Auto-Updater fully functional.

**Expected behavior**
Running the `gh-publish` script should properly build/bundle and ship all necessary file to GitHub and create a new release.

**Screenshots**
<img width="1199" alt="Screen Shot 2021-07-13 at 11 20 49 AM" src="https://user-images.githubusercontent.com/14981545/125537455-be7c6a04-882a-4111-80ed-26ec0683cfa7.png">

**Comment by nattiechan** [comment]
Thank you for raising this issue! It turns out that the MacOS environment is not entirely compatible with the packaging of the Linux version of the app. While electron builder has the ability for multi-platform build, the solutions (according to their docs) require a functional CI/CD pipeline like Travis CI or GitHub Action, which we do not have at the moment.

We worked around the issue by building the Linux package using the WSL environment. The files missing are now included in the v.1.13.0 release. We also included instructions on how to do so in a developer `readme` in the repository for future developers. Hope that helps!
